spring:
  security:
    user:
      name: user
      password: 12345
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Yoga-class-application
  datasource:
    url: jdbc:postgresql://localhost:5432/yoga-class-app
    username: mustafa
    password: 123456789
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: Debug

jwt:
  secret: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
  header: Authorization