management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/yoga-class-app
    username: user
    password: password
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
  security:
    user:
      name: user
      password: 12345
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
    include-application-name: false
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: Debug
keycloak:
  realm: spring
  server-url: http://localhost:8081
  client-id: springer
  client-secret: 8U8IZTotTElfAeSQUZ52CH8p60eC9Qnk
  grant-type: password
  name: mustafa
  password: admin
